admin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView
from vendas import views


urlpatterns = [
    path('erp/',include('erp.urls')),
    
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('home/',views.home, name='home'),
    path('logout/', views.my_logout, name="logout"),
    path('person/', views.persons_list, name="person"),
    # path('list/', views.persons_list, name="person_list"),
    path('new/', views.persons_new, name="person_new"),
    path('update/<int:id>/', views.persons_update, name="persons_update"),
    # path('delete/<int:id>/', views.persons_delete, name="persons_delete"),
    path('classificacao/', views.classificacao, name='fiscal_classificacao'),
    path('edit-classificacao/<int:id>/', views.edit_classificao, name='edit_classificacao_pk'),

    path('list/', views.IndexView.as_view(), name='index'),
    path('list/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('post/', views.postview, name='post'),
    path('delete/<int:pk>/', views.delete, name='delete'),

    

   

]

erp/urls.py
from django.contrib import admin
from django.urls import path

from erp import views


urlpatterns = [

     path('', views.RemanufaturaView.as_view(), name='remanufatura'),
     path('editremanufatura/<int:pk>/', views.edit, name='editremanufatura'),
]

vendas/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Empresa(models.Model):

    Status_CHOICES =[('Ativo','Ativo'),('Desativado','Desativado')]
    Nome = models.CharField(max_length=150)
    Tipo = models.CharField(choices=Status_CHOICES,default='Ativo',max_length=50)

    def __str__(self):
        return self.Nome


class Person(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    birth_date = models.DateField()
    location = models.CharField(max_length=100, blank=True)
    


class Classificacao(models.Model):
    codigo = models.CharField(max_length=15,unique=True)
    descricao = models.TextField()


    def __unicode__(self):
        return (self.codigo)

    def get_absolute_url(self):
        return reverse('edit_classificacao_pk', kwargs={'obj': self.pk})

class Post(models.Model):
    title = models.CharField(max_length=120, help_text='title of message.')
    message = models.TextField(help_text="what's on your mind ...")
 
    def __str__(self):
        return self.title

def validate_CNPJ(value):
    """
    Value can be either a string in the format XX.XXX.XXX/XXXX-XX or a
    group of 14 characters.
    :type value: object
    """
    value = str(value)
    if value in EMPTY_VALUES:
        return u''
    if not value.isdigit():
        value = re.sub("[-/\.]", "", value)
    orig_value = value[:]
    try:
        int(value)
    except ValueError:
        raise ValidationError(error_messages['digits_only'])
    if len(value) > 14:
        raise ValidationError(error_messages['max_digits'])
    orig_dv = value[-2:]

    new_1dv = sum([i * int(value[idx]) for idx, i in enumerate(list(range(5, 1, -1)) + list(range(9, 1, -1)))])
    new_1dv = DV_maker(new_1dv % 11)
    value = value[:-2] + str(new_1dv) + value[-1]
    new_2dv = sum([i * int(value[idx]) for idx, i in enumerate(list(range(6, 1, -1)) + list(range(9, 1, -1)))])
    new_2dv = DV_maker(new_2dv % 11)
    value = value[:-1] + str(new_2dv)
    if value[-2:] != orig_dv:
        raise ValidationError(error_messages['invalid'])

    return orig_value

class Clientes(models.Model):
    Status_CHOICES =[('Ativo','Ativo'),('Desativado','Desativado')]

    name = models.CharField(max_length=200)
    contato = models.CharField(max_length=200)
    emailcontato = models.EmailField(blank=True)
    emailfinanceiro = models.EmailField(blank=True)
    tipo = models.CharField(choices=Status_CHOICES,default='Ativo',max_length=50)
    datacadastro = models.DateField(auto_now=True)
    location = models.CharField(max_length=200, blank=True)
    cnpj = models.CharField(unique=True, max_length=14, validators=[validate_CNPJ])





    

vendas/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _
from .models import Person,Classificacao,Post
from django.forms import ModelForm
from django.db.models import Q

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'email', 'birth_date', 'location']


class FormQueryClassificacao(forms.Form):
    q = forms.CharField(required=False)

    def query(self):
        itens = Classificacao.objects.all()
        q = self.cleaned_data['q']
        if self.cleaned_data['q']:
           itens = itens.filter(Q(codigo__icontains=q) | Q(descricao__icontains=q) )
        return itens


class FormClassificacao(forms.ModelForm):
    class Meta:
        model = Classificacao
        fields = '__all__'


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

erp/views.py
from django.shortcuts import render
from .models import view_alertaremanufatura
from admin.contrib.generic_view import add_edit, list_view
from django.views.generic import ListView, DetailView
from .forms import RemanufaturaForm
from django.shortcuts import get_object_or_404,redirect
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.


class RemanufaturaView(ListView):
 template_name='vendas/remanufatura.html'
 context_object_name = 'remanufatura_list'
 def get_queryset(self):
  return view_alertaremanufatura.objects.all()


#Edit a post
def edit(request, pk, template_name='vendas/edit-remanufatura.html'):
    edit= get_object_or_404(view_alertaremanufatura, pk=pk)
    form = RemanufaturaForm(request.POST or None, instance=edit)
    if form.is_valid():
        # form.save()
        subject = 'Thank you for registering to our site'
        message = ' it  means a world to us '
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ['murilorodrigues@edgeglobalsupply.com.br',]
        send_mail( subject, message, email_from, recipient_list )
        return redirect('remanufatura')
    return render(request, template_name, {'form':form})

vendas/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout as django_logout
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
import json 
from tablib import Dataset
from .forms import PersonForm,FormQueryClassificacao,FormClassificacao
from .models import Person,Classificacao
from django.shortcuts import get_list_or_404, get_object_or_404
from django.forms import modelformset_factory
# from vendas.tables import PersonTable
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.utils.html import escape
from admin.contrib.generic_view import add_edit, list_view
from django.utils.translation import ugettext_lazy as _
from .forms import PostForm
from .models import Post
from django.core.mail import send_mail
from django.conf import settings


def home(request):
    return render(request,'vendas/home.html')


def my_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))
#     return redirect('home')

def logout(request):
    django_logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def user_json_lookup(request):
    # q = request.GET.get('q', '')
    # users = [u.get_json for u in User.objects.filter(Q(first_name__icontains=q) |Q(last_name__icontains=q) | Q(username__icontains=q) | Q(email__icontains=q)).order_by('first_name')]
    users = [u.get_json() for u in User.objects.all()]
    return HttpResponse(json.dumps(users), content_type='application/json')

def mylogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return render(request,'vendas/home.html')       


def simple_upload(request):
    if request.method == 'POST':
        person_resource = PersonResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            person_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'core/simple_upload.html')


@login_required
def persons_list(request):
    persons = PersonTable()
    return render(request, 'vendas/person.html',{'persons':persons})


@login_required
def persons_new(request):
    form = PersonForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return redirect('person_list')
    return render(request, 'vendas/person_form.html', {'form': form})


@login_required
def persons_update(request, id):
    person = get_object_or_404(Person, pk=id)
    form = PersonForm(request.POST or None, request.FILES or None, instance=person)

    if form.is_valid():
        form.save()
        return redirect('person_list')

    return render(request, 'vendas/person_form.html', {'form': form})


@login_required
def persons_delete(request, id):
    person = get_object_or_404(Person, pk=id)

    if request.method == 'POST':
        person.delete()
        return redirect('person_list')

    return render(request, 'vendas/person_delete_confirm.html', {'person': person})


@login_required
def edit_classificao(request, obj=None, template='vendas/classificacao.html'):
        return add_edit(request, Classificacao, FormClassificacao, template, 'fiscal_classificacao', obj=obj, pagetitle=_(u'Classificação Fiscal'))


@login_required
def classificacao(request, template='vendas/classificacoes.html'):
    return list_view(request, FormQueryClassificacao, template, pagetitle=_(u'Classificação Fiscal'), add_url='edit_classificacao')

#home view for posts. Posts are displayed in a list

class IndexView(ListView):
 template_name='vendas/list.html'
 context_object_name = 'post_list'
 def get_queryset(self):
  return Post.objects.all()

#Detail view (view post detail)
class PostDetailView(DetailView):
 model=Post
 template_name = 'vendas/post-detail.html'

#New post view (Create new post)
def postview(request):
 if request.method == 'POST':
  form = PostForm(request.POST)
  if form.is_valid():
   form.save()
  return redirect('index')
 form = PostForm()
 return render(request,'vendas/post.html',{'form': form})

#Edit a post
def edit(request, pk, template_name='vendas/edit.html'):
    post= get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('index')
    return render(request, template_name, {'form':form})

#Delete post
def delete(request, pk, template_name='vendas/confirm_delete.html'):
    post= get_object_or_404(Post, pk=pk)    
    if request.method=='POST':
        post.delete()
        return redirect('index')
    return render(request, template_name, {'object':post})

vendas/templates/vendas/backup_person.html
{% extends 'adminlte/base.html' %}


{% block title %} Administracao {% endblock %}

{% block content %}

    <div class="row">
        <div class="col">

        </div>
        <a href="{% url 'person_new' %}" class="btn btn-primary"> Novo cliente</a>
        <div class="col-6">
            <h3>Listagem de clientes</h3>
            <ul class="list-group">
                {% for person in persons %}
                    <li class="list-group-item">
                        <a href="{% url 'persons_update' person.id %}">{{ person.name }}</a>
                        <a href="{% url 'persons_delete' person.id %}" class="trash-item">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                    </li>

                {% endfor %}
            </ul>

            <br>

            

        </div>

        <div class="col">
            {% if user.is_authenticated %}
                <p>Ola {{user.username }}
                    <a href="{% url 'logout' %}">
                        <span class="badge badge-dark">Sair</span>
                    </a>
                </p>

            {% endif %}
        </div>
    </div>


{% endblock %}

vendas/templates/vendas/classificacao.html
{% extends 'generic_view/addedit.html' %}
{% block extra-head %}
    {{ block.super }}
    <style type="text/css">
        #id_name{width:632px;}
    </style>
{% endblock %}
{% block fields %}
    <div class="linha">
        <div class="coluna">
            <span class="form-label">Código:</span>
            {%include "include/field.html" with field=form.codigo%}
        </div>
        <div class="coluna">
            <span class="form-label">Descrição:</span>
            {%include "include/field.html" with field=form.descricao%}
        </div>

    </div>

{% endblock %}

vendas/templates/vendas/classificacoes.html
{% extends 'generic_view/list.html' %}
{% block extra-head %}
    {{ block.super }}
    <style type="text/css">
        #id_q{width: 300px;}
    </style>
{% endblock %}
{% block filter %}
    {{ form.q }}
{% endblock %}

{% block grid %}
    <table class="grid">
        <tr>
            <th></th>
            <th>Codigo</th>
            <th>Descrição</th>


            <th class="edit-column">Edit</th>
        </tr>
        {% for i in itens %}
            <tr class="{%cycle 'alt' ''%}">
                <td class="{%cycle 'yellow' 'green'%}"></td>
                <td>{{ i.codigo }}</td>
                <td>{{ i.descricao }}</td>

                <td class="edit-column">
                    <a href="{{ i.get_absolute_url }}">
                        <span class="fa fa-pencil-square-o icon-color" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

vendas/templates/vendas/confirm_delete.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Editar Post</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-row">
      <div class="alert alert-warning">
       Delete {{ object }}?
      </div>
    </div>
    <button type="submit" class="btn btn-danger">
     <span class="glyphicon glyphicon-trash"></span>
    </button>
  </form>
{% endblock %}

vendas/templates/vendas/edit-remanufatura.html
{% extends 'adminlte/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Editar Remanufatura</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}

vendas/templates/vendas/edit.html
{% extends 'adminlte/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Editar Post</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}

vendas/templates/vendas/home.html
{% extends 'adminlte/base.html' %}

{% block title %}My App{% endblock %}
{% block content %}
<section class="content">

    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-aqua"><i class="fa fa-envelope-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Mensagens</span>
            <span class="info-box-number">1,410</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-green"><i class="fa fa-flag-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Marcadores</span>
            <span class="info-box-number">410</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-yellow"><i class="fa fa-files-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Uploads</span>
            <span class="info-box-number">13,648</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-red"><i class="fa fa-star-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Likes</span>
            <span class="info-box-number">93,139</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- =========================================================== -->

    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-aqua">
          <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Bookmarks</span>
            <span class="info-box-number">41,410</span>

            <div class="progress">
              <div class="progress-bar" style="width: 70%"></div>
            </div>
                <span class="progress-description">
                  70% Increase in 30 Days
                </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-green">
          <span class="info-box-icon"><i class="fa fa-thumbs-o-up"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Likes</span>
            <span class="info-box-number">41,410</span>

            <div class="progress">
              <div class="progress-bar" style="width: 70%"></div>
            </div>
                <span class="progress-description">
                  70% Increase in 30 Days
                </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-yellow">
          <span class="info-box-icon"><i class="fa fa-calendar"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Events</span>
            <span class="info-box-number">41,410</span>

            <div class="progress">
              <div class="progress-bar" style="width: 70%"></div>
            </div>
                <span class="progress-description">
                  70% Increase in 30 Days
                </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-red">
          <span class="info-box-icon"><i class="fa fa-comments-o"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Comments</span>
            <span class="info-box-number">41,410</span>

            <div class="progress">
              <div class="progress-bar" style="width: 70%"></div>
            </div>
                <span class="progress-description">
                  70% Increase in 30 Days
                </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <!-- =========================================================== -->

    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>150</h3>

            <p>New Orders</p>
          </div>
          <div class="icon">
            <i class="fa fa-shopping-cart"></i>
          </div>
          <a href="#" class="small-box-footer">
            More info <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3>53<sup style="font-size: 20px">%</sup></h3>

            <p>Bounce Rate</p>
          </div>
          <div class="icon">
            <i class="ion ion-stats-bars"></i>
          </div>
          <a href="#" class="small-box-footer">
            More info <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
          <div class="inner">
            <h3>44</h3>

            <p>User Registrations</p>
          </div>
          <div class="icon">
            <i class="ion ion-person-add"></i>
          </div>
          <a href="#" class="small-box-footer">
            More info <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
          <div class="inner">
            <h3>65</h3>

            <p>Unique Visitors</p>
          </div>
          <div class="icon">
            <i class="ion ion-pie-graph"></i>
          </div>
          <a href="#" class="small-box-footer">
            More info <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
      <!-- ./col -->
    </div>
      

</section>
<!-- <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form> -->
{% endblock %}

vendas/templates/vendas/import.html
{% extends 'adminlte/base.html' %}

{% block title %}My App{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

vendas/templates/vendas/list.html
{% extends 'adminlte/base.html' %}
{% load static %}


{% block content %}



<div class="container-fluid">
 <div class="row">
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
   <div  class="col-md-10 col-xs-10 col-sm-10">
    <h3 class="round3" style="text-align:center;">Posts</h3>
  </div>
  <div class="col-md-1 col-xs-1 col-sm-1"></div>
 </div>
 <div class="row">
  <div class="col-md-10 col-xs-10 col-sm-10"></div>
  <div class="col-md-2 col-xs-1 col-sm-1">
   <br/>
            <a href="{% url 'post' %}">
              <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>
              </button>
            </a>
  </div>
 </div>
 <br/>
 <table class="table table-bordered table-hover dataTable">
   <tr>
      <th>Ações</th>
      <th>Titulo</th>
   </tr>


 {% for post in post_list %}
 <tr>
    <td><a href=" {% url 'detail' post.pk %}">
        <button type="button" class="btn btn-info">
         <span class="glyphicon glyphicon-open"></span>
        </button>&nbsp

        <a href="{% url 'edit' post.pk %}">
        <button type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-pencil"></span></button>&nbsp

        <a href=" {% url 'delete' post.pk %}">
        <button type="button" class="btn btn-danger">
        <span class="glyphicon glyphicon-trash"></span>
        </button>&nbsp
        
      </td>
    
    <td><a href="{% url 'detail' post.pk %}">{{ post.title }}</a></td>
 </tr>
 
 {% endfor %}
</table>
</div>


{% endblock %}

vendas/templates/vendas/person.html
{% extends 'adminlte/base.html' %}
{% load static %}
{% load table_tags %}


{% block title %} Administracao {% endblock %}

{% block content %}

    <div class="row">
        <div class="col">

        </div>
        <a href="{% url 'person_new' %}" class="btn btn-primary"> Novo cliente</a>
        <div class="col-6">
            <h3>Listagem de clientes</h3>
            {% render_table persons %}
            <br> 
        </div>

        <div class="col">
            {% if user.is_authenticated %}
                <p>Ola {{user.username }}
                    <a href="{% url 'logout' %}">
                        <span class="badge badge-dark">Sair</span>
                    </a>
                </p>

            {% endif %}
        </div>
    </div>


{% endblock %}

vendas/templates/vendas/person_form.html
{% extends 'adminlte/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Novo cliente</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}

vendas/templates/vendas/post-detail.html
{% extends 'adminlte/base.html' %}
{% load static %}


{% block content %}
<div class="container-fluid">
<div class="row"></div>
<br/>
<div class="row">
 <div class="col-md-1 col-xs-1 col-sm-1">
    </div>
 <div class="col-md-8 col-xs-8 col-sm-8">
  <p class="h2">
   {{post.title}}
  </p>
    </div>
 <div class="col-md-1 col-xs-1 col-sm-1">
  <a href="{% url 'edit' post.pk %}">
   <button type="button" class="btn btn-info">
    <span class="glyphicon glyphicon-pencil"></span>
   </button>
  </a>
 </div>
 <div class="col-md-1 col-xs-1 col-sm-1">
  <a href="{% url 'delete' post.pk %}">
   <button type="button" class="btn btn-danger">
    <span class="glyphicon glyphicon-trash"></span>
   </button>
  </a>
 </div>
 <div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
<div class="row">
 <div class="col-md-1 col-xs-1 col-sm-1"></div>
 <div class="col-md-10 col-xs-10 col-sm-10">
 {{post.message}}
 </div>
 <div class="col-md-1 col-xs-1 col-sm-1"></div>
</div>
</div>
{% endblock %}

vendas/templates/vendas/post.html
{% extends 'adminlte/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Novo cliente</h3>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
{% endblock %}

vendas/templates/vendas/remanufatura.html
{% extends 'adminlte/base.html' %}
{% load static %}


{% block content %}
<h3 class="round3" style="text-align:center;">Controle Remanufatura</h3>

<table class="table table-bordered table-hover dataTable">
   <tr>
      <th>Ações</th>
      <th>Empresa</th>
      <th>Chave</th>
      <th>Nota</th>
      <th>Emissão</th>
      <th>Entidade</th>
      <th>Aviso</th>
      
   </tr>
 {% for remanufatura in remanufatura_list %}
 <tr>
    <td><a href="{% url 'editremanufatura' remanufatura.pk %}">
      <button type="button" class="btn btn-info">
       <span class="glyphicon glyphicon-pencil"></span></button>&nbsp</td>
       <td><a href="">{{ remanufatura.empresa }}</a></td>
       <td><a href="">{{ remanufatura.chave }}</a></td>
       <td><a href="">{{ remanufatura.nota }}</a></td>
       <td><a href="">{{ remanufatura.emissao }}</a></td>
       <td><a href="">{{ remanufatura.entidade }}</a></td>
       <td><a href="">{{ remanufatura.aviso }}</a></td>
 </tr>
 
 {% endfor %}
</table>
</div>


{% endblock %}